trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: CopyFiles@2
      displayName: Copy build files to staging directory
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'  # Folder with your build files
        Contents: '**/*'                          # Copy all files and folders
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Folder to copy files to

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Publish the files from artifact staging directory
        ArtifactName: 'drop'
        publishLocation: 'Container'
